# Uncomment the next line to define a global platform for your project
platform :ios, '16.4'

target 'HabitTracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HabitTracker
  pod "Apollo"

  target 'HabitTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HabitTrackerUITests' do
    # Pods for testing
  end

end
